Adding Deconvolution functionality for MXNet throwing unsupported exc…
awslabs/djl pull request #168
Opened 2020-09-24 01:28 UTC by euromutt

…eptions for others.

## Channel for questions ##
Before or while filing an issue please feel free to join our [Slack channel](https://join.slack.com/t/deepjavalibrary/shared_invite/zt-ar91gjkz-qbXhr1l~LFGEIEeGBibT7w) to get in touch with development team, ask questions, find out what's cooking and more!

## Description ##
(Brief description of what this PR is about)

## Checklist ##
### Essentials ###
Please feel free to remove inapplicable items for your PR.
- [ ] Changes are complete (i.e. I finished coding on this PR)
- [ ] All changes have test coverage:
- [x] Code is well-documented: 
    - For user-facing API changes, Java doc has been updated. 
    - For new examples, README.md is added to explain the what the example does.
- [x] To the my best knowledge, [examples](https://github.com/awslabs/djl/tree/master/examples) and [jupyter notebooks](https://github.com/awslabs/djl/tree/master/jupyter) are either not affected by this change, or have been fixed to be compatible with this change

### Changes ###
- [x] MXNDArrayEX, tests, (and when applicable, Java doc)
- [x] PtNDArrayEX, tests, (and when applicable, Java doc)
- [x] TfNDArrayEX, tests, (and when applicable, Java doc)
- [x] NDArrayEX, tests, (and when applicable, Java doc)

## Comments ##
- Adding transpose convolution blocks allows convolutional autoencoders and generative adversarial networks to be built in DJL.

2020-09-24 16:16 UTC, frankfliu reviewed
@euromutt 
I made some cosmetic changes to your PR:
1. reformatted your java code, please format your java code before commit next time:
```
./gradlew formatJava
```
2. Fixed javadoc and checkstyle violations, you can run the following command to check:
```
./gradlew check -x test
```

2020-09-24 20:21 UTC, stu1130 reviewed
Thanks for your contribution!

Generally, it looks great!
you can add unit test on [BlockCoreTest.java](https://github.com/awslabs/djl/blob/master/integration/src/main/java/ai/djl/integration/tests/nn/BlockCoreTest.java) as Lai suggested and use the following command to run it
```
./gradlew :integration:run -Dai.djl.default_engine=MXNet
```

2020-09-24 20:21 UTC, stu1130 commented on api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
> +    private static final byte VERSION = 3;
this should be version 1

2020-09-24 20:21 UTC, stu1130 commented on api/src/main/java/ai/djl/nn/convolutional/Conv1dTranspose.java
> +    public static NDList conv1dtranspose(NDArray input, NDArray weight) {
```suggestion
    public static NDList conv1dTranspose(NDArray input, NDArray weight) {
```
same applies to the rest

2020-09-25 17:11 UTC, frankfliu reviewed
Please add a test in BlockCoreTest.

2020-09-25 17:11 UTC, frankfliu commented on api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
> +    private static final byte VERSION = 3;
```suggestion
    private static final byte VERSION = 1;
```

2020-09-25 17:11 UTC, frankfliu commented on api/src/main/java/ai/djl/nn/convolutional/Deconvolution.java
> +        } else if (version != 1) {
```suggestion
        } else {
```

2020-09-29 17:49 UTC, lanking520 commented
LGTM overall. The remaining part is just to add an test in the integration sections

2020-09-29 18:09 UTC, euromutt commented
Sorry for the delay, I was in the middle of final exams. I will work the tests today or tomorrow.

Cheers,
Josh

2020-09-30 18:33 UTC, euromutt commented
I've added tests for Conv1dTranspose and Conv2dTranspose in BlockCoreTest, but ./gradlew :integration:run -Dai.djl.default_engine=MXNet is failing (see output below). Is this a known issue?

Task :integration:run FAILED
[INFO ] - Running test ai.djl.integration.tests.model_zoo.CustomTranslatorTest ...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integration:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 139

2020-10-01 16:52 UTC, lanking520 requested changes
Seemed the rebase caused some issue. need to address

2020-10-01 16:52 UTC, lanking520 commented on api/src/main/java/ai/djl/nn/convolutional/Conv1dTranspose.java
> +<<<<<<<<< Temporary merge branch 1
need resolve confilict here

2020-10-01 16:52 UTC, lanking520 commented on api/src/main/java/ai/djl/nn/convolutional/Conv2dTranspose.java
> +=========
need resolve conflict here

2020-10-01 16:52 UTC, lanking520 commented on build.gradle
> +    id "com.github.spotbugs" version "2.0.0" apply false
Seemed merging causing some issue

2020-10-01 22:40 UTC, lanking520 commented
It seemed you accidentally use an old build (DJL 0.4.0) to develop and now it conflict with the major version

2020-10-01 23:46 UTC, euromutt commented
There was a weird merge when I added the test, I assumed it was related to the 0.8 release, but clearly that was not the case. I'm going to kill my fork and resubmit the PR.

2020-10-02 00:25 UTC, closed without merging