YoloV5 inference support of ONNX models
awslabs/djl pull request #272
Opened 2020-11-04 13:14 UTC by thhart

## Description ##
adds support for YoloV5 object detection models via ONNX

### Changes ###
added YoloV5Translator with following features: input squeezer, output parser and non max suppression boxes

### Howto ###
YoloV5 supports at least two output formats, to use models here it is important to specify model.model[-1].export = False  in export.py.
An ONNX export can be done like this: https://github.com/ultralytics/yolov5/issues/251

## Example ##

```
         final YoloV5Translator translator = new YoloV5Translator(YoloV5Translator.builder().optSynsetArtifactName("synset.txt"));
         Criteria<Image, DetectedObjects> criteria = Criteria.builder()
               .setTypes(Image.class, DetectedObjects.class) // defines input and output data type
               .optDevice(Device.cpu())
               .optTranslator(translator)
               .optModelUrls("file:///path-to-model/") // search models in specified path
               .optModelName("yolov5-exported-model.onnx")
               .optEngine("OnnxRuntime")
               .build();
         final ZooModel<Image, DetectedObjects> model = ModelZoo.loadModel(criteria);
         Predictor<Image, DetectedObjects> predictor = model.newPredictor(translator);
         final File input = new File("a-file-to-analyze.jpg");
         BufferedImageFactory factory = new BufferedImageFactory();
         final BufferedImage ix = HelperImage.scaleImage(ImageIO.read(input), widthOfModel, heightOfModel);
         DetectedObjects detection = predictor.predict(factory.fromImage(ix));
```

2020-11-04 18:07 UTC, stu1130 reviewed
Thanks for your contribution!
Could you run
`./gradlew fJ build`

2020-11-04 18:07 UTC, stu1130 commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +      List<java.lang.Double> retProbs = new ArrayList<>();
nit: 
```suggestion
      List<Double> retProbs = new ArrayList<>();
```

2020-11-04 18:07 UTC, stu1130 commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> + * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
nit:2020

2020-11-04 18:07 UTC, stu1130 commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +                        return java.lang.Double.compare(rhs.getConfidence(), lhs.getConfidence());
```suggestion
                        Double.compare(rhs.getConfidence(), lhs.getConfidence());
```

2020-11-04 18:30 UTC, frankfliu requested changes

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +import java.awt.geom.Rectangle2D;
We should avoid using awt package if possible, awt package is not portable. It doesn't work on Android.
You can use: ai.djl.modality.cv.output.Rectangle

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +import ai.djl.modality.cv.output.*;
Avoid wildcard import

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +   public enum YOLO_OUTPUT_TYPE {
1. enum name should be: YolyOuputType
2. class should be at the end of the class,

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +   private double nmsThresh = 0.4F;
```suggestion
   private double nmsThresh = 0.4;
```

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +   private final YOLO_OUTPUT_TYPE yoloOutputLayerType;
avoid final member modifier for simplicity and readability.

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> + A translator for yolo V5 models. This was tested with ONNX exported Yolo models.
```suggestion
 * A translator for yolo V5 models. This was tested with ONNX exported Yolo models.
```

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> + For details check here: https://github.com/ultralytics/yolov5
Java doc requires * at each line

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +   public double getNmsThresh() {
public method requires JavaDoc

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +   protected DetectedObjects nms(ArrayList<IntermediateResult> list) {
```suggestion
   protected DetectedObjects nms(List<IntermediateResult> list) {
```

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +      final NDArray ndArray = list.get(0);
Avoid "final" for local variable

2020-11-04 18:30 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +         pipeline = new Pipeline().add(array -> array.transpose(2, 0, 1).toType(DataType.FLOAT32, false).div(255));
Move this to build() method.
pipeline could be manually set in the builder, We should create pipeline only if user didn't set pipeline.

2020-11-04 21:09 UTC, frankfliu reviewed
This looks good to me.

Would you mind import this mode into ONNX runtime model zoo in separate PR?

2020-11-04 21:09 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> + * Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```suggestion
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```

2020-11-04 21:09 UTC, frankfliu commented on api/src/main/java/ai/djl/modality/cv/translator/YoloV5Translator.java
> +        private IntermediateResult(
```suggestion
       IntermediateResult(
```

2020-11-04 21:21 UTC, thhart commented
> Would you mind import this mode into ONNX runtime model zoo in separate PR?
Please note I use DJL with own models however I can understand it can be good to have a sample model available and also for testing maybe, if I find some time I will take a standard model.

2020-11-04 22:43 UTC, frankfliu approved these changes

2020-11-04 22:43 UTC, merged

2021-05-30 18:02 UTC, hongyaohongyao commented
cost memory leak