adding torch_cuda*
awslabs/djl pull request #850
Opened 2021-04-12 21:10 UTC by goswamig

## Description ##

Brief description of what this PR is about

- If this change is a backward incompatible change, why must this change be made?
- Interesting edge cases to note here

2021-04-12 21:12 UTC, frankfliu approved these changes

2021-04-12 21:31 UTC, lanking520 requested changes
download links needs to be fixed as well

2021-04-12 22:14 UTC, goswamig commented
> download links needs to be fixed as well

done.

2021-04-13 00:49 UTC, lanking520 approved these changes

2021-04-13 00:50 UTC, merged